### PR TITLE
Windows file fixes

### PR DESCRIPTION
**Pull request by jeeger**
Made tar extraction work on windows, along with some added niceties like filename transformation and detection of overlong filenames.

### CODE REVIEW

**Comment by kidd** [comment]
looks good! Thanks for working on this long standing issue @jeeger. 

I'm gonna find some time to try the branch in linux and merge it asap.

**Comment by jeeger** [comment]
Please do! Also someone who is a Windows user can try the Haskell fileset to check whether the "long filename" warning works correctly.

**Comment by kidd** [comment]
Tried briefly on linux and works. In! 

Thanks for your contribution

**Comment by gilbertw1** [comment]
FYI, I fixed a few minor issues here in my running fork: https://github.com/gilbertw1/dash-docs/commit/8b7f336b76631fd7d1e7203ba7c869bcea585ebd

**Comment by jeeger** [comment]
That should probably be merged as well, as the code I've written for the overlong filename warning was pretty much off-the-cuff :confused:

**Pull request merged**
