### PR TITLE
Fix #96 by making each docset its own Helm source.

### LINKED ISSUE #96: make each docset to appear as a separate source
Would be possible to have a multisource view - one source per doc set. It feels a bit unnatural  to have all the docs in one bulk to me.

helm

### PR DESCRIPTION
**Pull request by xiongtx**

### CODE REVIEW

**Comment by kidd** [comment]
Thanks for your contribution!

I've just learned that with <left> and <right> (and c-o) you can navigate through different sources so this is definately much more than a cosmetic change :).

**Comment by xiongtx** [comment]
That's not all you can do.

Within a particular source, <kbd>C-M-a</kbd> calls `helm-show-all-in-this-source-only`, which, as the name suggests, shows only candidates from a single source. Thus, you can search within a single docset.

You can show all sources again with <kbd>C-M-e</kbd>, bound to `helm-display-all-sources`.

**Comment by kidd** [comment]
cool!

**Comment by areina** [comment]
Hey @xiongtx , thank you so much, this is really helpful.

**Pull request merged**
